# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/izapreev/Projects/bti

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/izapreev/Projects/bti

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/izapreev/Projects/bti/CMakeFiles /Users/izapreev/Projects/bti/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/izapreev/Projects/bti/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bpbd-client

# Build rule for target.
bpbd-client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bpbd-client
.PHONY : bpbd-client

# fast build rule for target.
bpbd-client/fast:
	$(MAKE) -f CMakeFiles/bpbd-client.dir/build.make CMakeFiles/bpbd-client.dir/build
.PHONY : bpbd-client/fast

#=============================================================================
# Target rules for targets named bpbd-processor

# Build rule for target.
bpbd-processor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bpbd-processor
.PHONY : bpbd-processor

# fast build rule for target.
bpbd-processor/fast:
	$(MAKE) -f CMakeFiles/bpbd-processor.dir/build.make CMakeFiles/bpbd-processor.dir/build
.PHONY : bpbd-processor/fast

#=============================================================================
# Target rules for targets named bpbd-balancer

# Build rule for target.
bpbd-balancer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bpbd-balancer
.PHONY : bpbd-balancer

# fast build rule for target.
bpbd-balancer/fast:
	$(MAKE) -f CMakeFiles/bpbd-balancer.dir/build.make CMakeFiles/bpbd-balancer.dir/build
.PHONY : bpbd-balancer/fast

#=============================================================================
# Target rules for targets named bpbd-server

# Build rule for target.
bpbd-server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bpbd-server
.PHONY : bpbd-server

# fast build rule for target.
bpbd-server/fast:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/build
.PHONY : bpbd-server/fast

#=============================================================================
# Target rules for targets named lm-query

# Build rule for target.
lm-query: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lm-query
.PHONY : lm-query

# fast build rule for target.
lm-query/fast:
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/build
.PHONY : lm-query/fast

src/balancer/balancer_job.o: src/balancer/balancer_job.cpp.o

.PHONY : src/balancer/balancer_job.o

# target to build an object file
src/balancer/balancer_job.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-balancer.dir/build.make CMakeFiles/bpbd-balancer.dir/src/balancer/balancer_job.cpp.o
.PHONY : src/balancer/balancer_job.cpp.o

src/balancer/balancer_job.i: src/balancer/balancer_job.cpp.i

.PHONY : src/balancer/balancer_job.i

# target to preprocess a source file
src/balancer/balancer_job.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-balancer.dir/build.make CMakeFiles/bpbd-balancer.dir/src/balancer/balancer_job.cpp.i
.PHONY : src/balancer/balancer_job.cpp.i

src/balancer/balancer_job.s: src/balancer/balancer_job.cpp.s

.PHONY : src/balancer/balancer_job.s

# target to generate assembly for a file
src/balancer/balancer_job.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-balancer.dir/build.make CMakeFiles/bpbd-balancer.dir/src/balancer/balancer_job.cpp.s
.PHONY : src/balancer/balancer_job.cpp.s

src/balancer/balancer_parameters.o: src/balancer/balancer_parameters.cpp.o

.PHONY : src/balancer/balancer_parameters.o

# target to build an object file
src/balancer/balancer_parameters.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-balancer.dir/build.make CMakeFiles/bpbd-balancer.dir/src/balancer/balancer_parameters.cpp.o
.PHONY : src/balancer/balancer_parameters.cpp.o

src/balancer/balancer_parameters.i: src/balancer/balancer_parameters.cpp.i

.PHONY : src/balancer/balancer_parameters.i

# target to preprocess a source file
src/balancer/balancer_parameters.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-balancer.dir/build.make CMakeFiles/bpbd-balancer.dir/src/balancer/balancer_parameters.cpp.i
.PHONY : src/balancer/balancer_parameters.cpp.i

src/balancer/balancer_parameters.s: src/balancer/balancer_parameters.cpp.s

.PHONY : src/balancer/balancer_parameters.s

# target to generate assembly for a file
src/balancer/balancer_parameters.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-balancer.dir/build.make CMakeFiles/bpbd-balancer.dir/src/balancer/balancer_parameters.cpp.s
.PHONY : src/balancer/balancer_parameters.cpp.s

src/balancer/bpbd_balancer.o: src/balancer/bpbd_balancer.cpp.o

.PHONY : src/balancer/bpbd_balancer.o

# target to build an object file
src/balancer/bpbd_balancer.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-balancer.dir/build.make CMakeFiles/bpbd-balancer.dir/src/balancer/bpbd_balancer.cpp.o
.PHONY : src/balancer/bpbd_balancer.cpp.o

src/balancer/bpbd_balancer.i: src/balancer/bpbd_balancer.cpp.i

.PHONY : src/balancer/bpbd_balancer.i

# target to preprocess a source file
src/balancer/bpbd_balancer.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-balancer.dir/build.make CMakeFiles/bpbd-balancer.dir/src/balancer/bpbd_balancer.cpp.i
.PHONY : src/balancer/bpbd_balancer.cpp.i

src/balancer/bpbd_balancer.s: src/balancer/bpbd_balancer.cpp.s

.PHONY : src/balancer/bpbd_balancer.s

# target to generate assembly for a file
src/balancer/bpbd_balancer.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-balancer.dir/build.make CMakeFiles/bpbd-balancer.dir/src/balancer/bpbd_balancer.cpp.s
.PHONY : src/balancer/bpbd_balancer.cpp.s

src/balancer/translator_adapter.o: src/balancer/translator_adapter.cpp.o

.PHONY : src/balancer/translator_adapter.o

# target to build an object file
src/balancer/translator_adapter.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-balancer.dir/build.make CMakeFiles/bpbd-balancer.dir/src/balancer/translator_adapter.cpp.o
.PHONY : src/balancer/translator_adapter.cpp.o

src/balancer/translator_adapter.i: src/balancer/translator_adapter.cpp.i

.PHONY : src/balancer/translator_adapter.i

# target to preprocess a source file
src/balancer/translator_adapter.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-balancer.dir/build.make CMakeFiles/bpbd-balancer.dir/src/balancer/translator_adapter.cpp.i
.PHONY : src/balancer/translator_adapter.cpp.i

src/balancer/translator_adapter.s: src/balancer/translator_adapter.cpp.s

.PHONY : src/balancer/translator_adapter.s

# target to generate assembly for a file
src/balancer/translator_adapter.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-balancer.dir/build.make CMakeFiles/bpbd-balancer.dir/src/balancer/translator_adapter.cpp.s
.PHONY : src/balancer/translator_adapter.cpp.s

src/client/bpbd_client.o: src/client/bpbd_client.cpp.o

.PHONY : src/client/bpbd_client.o

# target to build an object file
src/client/bpbd_client.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-client.dir/build.make CMakeFiles/bpbd-client.dir/src/client/bpbd_client.cpp.o
.PHONY : src/client/bpbd_client.cpp.o

src/client/bpbd_client.i: src/client/bpbd_client.cpp.i

.PHONY : src/client/bpbd_client.i

# target to preprocess a source file
src/client/bpbd_client.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-client.dir/build.make CMakeFiles/bpbd-client.dir/src/client/bpbd_client.cpp.i
.PHONY : src/client/bpbd_client.cpp.i

src/client/bpbd_client.s: src/client/bpbd_client.cpp.s

.PHONY : src/client/bpbd_client.s

# target to generate assembly for a file
src/client/bpbd_client.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-client.dir/build.make CMakeFiles/bpbd-client.dir/src/client/bpbd_client.cpp.s
.PHONY : src/client/bpbd_client.cpp.s

src/client/messaging/messaging.o: src/client/messaging/messaging.cpp.o

.PHONY : src/client/messaging/messaging.o

# target to build an object file
src/client/messaging/messaging.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-client.dir/build.make CMakeFiles/bpbd-client.dir/src/client/messaging/messaging.cpp.o
	$(MAKE) -f CMakeFiles/bpbd-balancer.dir/build.make CMakeFiles/bpbd-balancer.dir/src/client/messaging/messaging.cpp.o
.PHONY : src/client/messaging/messaging.cpp.o

src/client/messaging/messaging.i: src/client/messaging/messaging.cpp.i

.PHONY : src/client/messaging/messaging.i

# target to preprocess a source file
src/client/messaging/messaging.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-client.dir/build.make CMakeFiles/bpbd-client.dir/src/client/messaging/messaging.cpp.i
	$(MAKE) -f CMakeFiles/bpbd-balancer.dir/build.make CMakeFiles/bpbd-balancer.dir/src/client/messaging/messaging.cpp.i
.PHONY : src/client/messaging/messaging.cpp.i

src/client/messaging/messaging.s: src/client/messaging/messaging.cpp.s

.PHONY : src/client/messaging/messaging.s

# target to generate assembly for a file
src/client/messaging/messaging.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-client.dir/build.make CMakeFiles/bpbd-client.dir/src/client/messaging/messaging.cpp.s
	$(MAKE) -f CMakeFiles/bpbd-balancer.dir/build.make CMakeFiles/bpbd-balancer.dir/src/client/messaging/messaging.cpp.s
.PHONY : src/client/messaging/messaging.cpp.s

src/client/trans_job_status.o: src/client/trans_job_status.cpp.o

.PHONY : src/client/trans_job_status.o

# target to build an object file
src/client/trans_job_status.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-client.dir/build.make CMakeFiles/bpbd-client.dir/src/client/trans_job_status.cpp.o
.PHONY : src/client/trans_job_status.cpp.o

src/client/trans_job_status.i: src/client/trans_job_status.cpp.i

.PHONY : src/client/trans_job_status.i

# target to preprocess a source file
src/client/trans_job_status.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-client.dir/build.make CMakeFiles/bpbd-client.dir/src/client/trans_job_status.cpp.i
.PHONY : src/client/trans_job_status.cpp.i

src/client/trans_job_status.s: src/client/trans_job_status.cpp.s

.PHONY : src/client/trans_job_status.s

# target to generate assembly for a file
src/client/trans_job_status.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-client.dir/build.make CMakeFiles/bpbd-client.dir/src/client/trans_job_status.cpp.s
.PHONY : src/client/trans_job_status.cpp.s

src/common/messaging/language_registry.o: src/common/messaging/language_registry.cpp.o

.PHONY : src/common/messaging/language_registry.o

# target to build an object file
src/common/messaging/language_registry.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-processor.dir/build.make CMakeFiles/bpbd-processor.dir/src/common/messaging/language_registry.cpp.o
	$(MAKE) -f CMakeFiles/bpbd-balancer.dir/build.make CMakeFiles/bpbd-balancer.dir/src/common/messaging/language_registry.cpp.o
.PHONY : src/common/messaging/language_registry.cpp.o

src/common/messaging/language_registry.i: src/common/messaging/language_registry.cpp.i

.PHONY : src/common/messaging/language_registry.i

# target to preprocess a source file
src/common/messaging/language_registry.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-processor.dir/build.make CMakeFiles/bpbd-processor.dir/src/common/messaging/language_registry.cpp.i
	$(MAKE) -f CMakeFiles/bpbd-balancer.dir/build.make CMakeFiles/bpbd-balancer.dir/src/common/messaging/language_registry.cpp.i
.PHONY : src/common/messaging/language_registry.cpp.i

src/common/messaging/language_registry.s: src/common/messaging/language_registry.cpp.s

.PHONY : src/common/messaging/language_registry.s

# target to generate assembly for a file
src/common/messaging/language_registry.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-processor.dir/build.make CMakeFiles/bpbd-processor.dir/src/common/messaging/language_registry.cpp.s
	$(MAKE) -f CMakeFiles/bpbd-balancer.dir/build.make CMakeFiles/bpbd-balancer.dir/src/common/messaging/language_registry.cpp.s
.PHONY : src/common/messaging/language_registry.cpp.s

src/common/messaging/messaging.o: src/common/messaging/messaging.cpp.o

.PHONY : src/common/messaging/messaging.o

# target to build an object file
src/common/messaging/messaging.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-client.dir/build.make CMakeFiles/bpbd-client.dir/src/common/messaging/messaging.cpp.o
	$(MAKE) -f CMakeFiles/bpbd-processor.dir/build.make CMakeFiles/bpbd-processor.dir/src/common/messaging/messaging.cpp.o
	$(MAKE) -f CMakeFiles/bpbd-balancer.dir/build.make CMakeFiles/bpbd-balancer.dir/src/common/messaging/messaging.cpp.o
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/common/messaging/messaging.cpp.o
.PHONY : src/common/messaging/messaging.cpp.o

src/common/messaging/messaging.i: src/common/messaging/messaging.cpp.i

.PHONY : src/common/messaging/messaging.i

# target to preprocess a source file
src/common/messaging/messaging.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-client.dir/build.make CMakeFiles/bpbd-client.dir/src/common/messaging/messaging.cpp.i
	$(MAKE) -f CMakeFiles/bpbd-processor.dir/build.make CMakeFiles/bpbd-processor.dir/src/common/messaging/messaging.cpp.i
	$(MAKE) -f CMakeFiles/bpbd-balancer.dir/build.make CMakeFiles/bpbd-balancer.dir/src/common/messaging/messaging.cpp.i
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/common/messaging/messaging.cpp.i
.PHONY : src/common/messaging/messaging.cpp.i

src/common/messaging/messaging.s: src/common/messaging/messaging.cpp.s

.PHONY : src/common/messaging/messaging.s

# target to generate assembly for a file
src/common/messaging/messaging.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-client.dir/build.make CMakeFiles/bpbd-client.dir/src/common/messaging/messaging.cpp.s
	$(MAKE) -f CMakeFiles/bpbd-processor.dir/build.make CMakeFiles/bpbd-processor.dir/src/common/messaging/messaging.cpp.s
	$(MAKE) -f CMakeFiles/bpbd-balancer.dir/build.make CMakeFiles/bpbd-balancer.dir/src/common/messaging/messaging.cpp.s
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/common/messaging/messaging.cpp.s
.PHONY : src/common/messaging/messaging.cpp.s

src/common/messaging/trans_job_code.o: src/common/messaging/trans_job_code.cpp.o

.PHONY : src/common/messaging/trans_job_code.o

# target to build an object file
src/common/messaging/trans_job_code.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-client.dir/build.make CMakeFiles/bpbd-client.dir/src/common/messaging/trans_job_code.cpp.o
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/common/messaging/trans_job_code.cpp.o
.PHONY : src/common/messaging/trans_job_code.cpp.o

src/common/messaging/trans_job_code.i: src/common/messaging/trans_job_code.cpp.i

.PHONY : src/common/messaging/trans_job_code.i

# target to preprocess a source file
src/common/messaging/trans_job_code.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-client.dir/build.make CMakeFiles/bpbd-client.dir/src/common/messaging/trans_job_code.cpp.i
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/common/messaging/trans_job_code.cpp.i
.PHONY : src/common/messaging/trans_job_code.cpp.i

src/common/messaging/trans_job_code.s: src/common/messaging/trans_job_code.cpp.s

.PHONY : src/common/messaging/trans_job_code.s

# target to generate assembly for a file
src/common/messaging/trans_job_code.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-client.dir/build.make CMakeFiles/bpbd-client.dir/src/common/messaging/trans_job_code.cpp.s
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/common/messaging/trans_job_code.cpp.s
.PHONY : src/common/messaging/trans_job_code.cpp.s

src/common/utils/logging/logger.o: src/common/utils/logging/logger.cpp.o

.PHONY : src/common/utils/logging/logger.o

# target to build an object file
src/common/utils/logging/logger.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-client.dir/build.make CMakeFiles/bpbd-client.dir/src/common/utils/logging/logger.cpp.o
	$(MAKE) -f CMakeFiles/bpbd-processor.dir/build.make CMakeFiles/bpbd-processor.dir/src/common/utils/logging/logger.cpp.o
	$(MAKE) -f CMakeFiles/bpbd-balancer.dir/build.make CMakeFiles/bpbd-balancer.dir/src/common/utils/logging/logger.cpp.o
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/common/utils/logging/logger.cpp.o
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/common/utils/logging/logger.cpp.o
.PHONY : src/common/utils/logging/logger.cpp.o

src/common/utils/logging/logger.i: src/common/utils/logging/logger.cpp.i

.PHONY : src/common/utils/logging/logger.i

# target to preprocess a source file
src/common/utils/logging/logger.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-client.dir/build.make CMakeFiles/bpbd-client.dir/src/common/utils/logging/logger.cpp.i
	$(MAKE) -f CMakeFiles/bpbd-processor.dir/build.make CMakeFiles/bpbd-processor.dir/src/common/utils/logging/logger.cpp.i
	$(MAKE) -f CMakeFiles/bpbd-balancer.dir/build.make CMakeFiles/bpbd-balancer.dir/src/common/utils/logging/logger.cpp.i
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/common/utils/logging/logger.cpp.i
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/common/utils/logging/logger.cpp.i
.PHONY : src/common/utils/logging/logger.cpp.i

src/common/utils/logging/logger.s: src/common/utils/logging/logger.cpp.s

.PHONY : src/common/utils/logging/logger.s

# target to generate assembly for a file
src/common/utils/logging/logger.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-client.dir/build.make CMakeFiles/bpbd-client.dir/src/common/utils/logging/logger.cpp.s
	$(MAKE) -f CMakeFiles/bpbd-processor.dir/build.make CMakeFiles/bpbd-processor.dir/src/common/utils/logging/logger.cpp.s
	$(MAKE) -f CMakeFiles/bpbd-balancer.dir/build.make CMakeFiles/bpbd-balancer.dir/src/common/utils/logging/logger.cpp.s
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/common/utils/logging/logger.cpp.s
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/common/utils/logging/logger.cpp.s
.PHONY : src/common/utils/logging/logger.cpp.s

src/common/utils/monitor/statistics_monitor.o: src/common/utils/monitor/statistics_monitor.cpp.o

.PHONY : src/common/utils/monitor/statistics_monitor.o

# target to build an object file
src/common/utils/monitor/statistics_monitor.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-processor.dir/build.make CMakeFiles/bpbd-processor.dir/src/common/utils/monitor/statistics_monitor.cpp.o
	$(MAKE) -f CMakeFiles/bpbd-balancer.dir/build.make CMakeFiles/bpbd-balancer.dir/src/common/utils/monitor/statistics_monitor.cpp.o
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/common/utils/monitor/statistics_monitor.cpp.o
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/common/utils/monitor/statistics_monitor.cpp.o
.PHONY : src/common/utils/monitor/statistics_monitor.cpp.o

src/common/utils/monitor/statistics_monitor.i: src/common/utils/monitor/statistics_monitor.cpp.i

.PHONY : src/common/utils/monitor/statistics_monitor.i

# target to preprocess a source file
src/common/utils/monitor/statistics_monitor.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-processor.dir/build.make CMakeFiles/bpbd-processor.dir/src/common/utils/monitor/statistics_monitor.cpp.i
	$(MAKE) -f CMakeFiles/bpbd-balancer.dir/build.make CMakeFiles/bpbd-balancer.dir/src/common/utils/monitor/statistics_monitor.cpp.i
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/common/utils/monitor/statistics_monitor.cpp.i
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/common/utils/monitor/statistics_monitor.cpp.i
.PHONY : src/common/utils/monitor/statistics_monitor.cpp.i

src/common/utils/monitor/statistics_monitor.s: src/common/utils/monitor/statistics_monitor.cpp.s

.PHONY : src/common/utils/monitor/statistics_monitor.s

# target to generate assembly for a file
src/common/utils/monitor/statistics_monitor.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-processor.dir/build.make CMakeFiles/bpbd-processor.dir/src/common/utils/monitor/statistics_monitor.cpp.s
	$(MAKE) -f CMakeFiles/bpbd-balancer.dir/build.make CMakeFiles/bpbd-balancer.dir/src/common/utils/monitor/statistics_monitor.cpp.s
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/common/utils/monitor/statistics_monitor.cpp.s
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/common/utils/monitor/statistics_monitor.cpp.s
.PHONY : src/common/utils/monitor/statistics_monitor.cpp.s

src/processor/bpbd_processor.o: src/processor/bpbd_processor.cpp.o

.PHONY : src/processor/bpbd_processor.o

# target to build an object file
src/processor/bpbd_processor.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-processor.dir/build.make CMakeFiles/bpbd-processor.dir/src/processor/bpbd_processor.cpp.o
.PHONY : src/processor/bpbd_processor.cpp.o

src/processor/bpbd_processor.i: src/processor/bpbd_processor.cpp.i

.PHONY : src/processor/bpbd_processor.i

# target to preprocess a source file
src/processor/bpbd_processor.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-processor.dir/build.make CMakeFiles/bpbd-processor.dir/src/processor/bpbd_processor.cpp.i
.PHONY : src/processor/bpbd_processor.cpp.i

src/processor/bpbd_processor.s: src/processor/bpbd_processor.cpp.s

.PHONY : src/processor/bpbd_processor.s

# target to generate assembly for a file
src/processor/bpbd_processor.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-processor.dir/build.make CMakeFiles/bpbd-processor.dir/src/processor/bpbd_processor.cpp.s
.PHONY : src/processor/bpbd_processor.cpp.s

src/processor/processor_job.o: src/processor/processor_job.cpp.o

.PHONY : src/processor/processor_job.o

# target to build an object file
src/processor/processor_job.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-processor.dir/build.make CMakeFiles/bpbd-processor.dir/src/processor/processor_job.cpp.o
.PHONY : src/processor/processor_job.cpp.o

src/processor/processor_job.i: src/processor/processor_job.cpp.i

.PHONY : src/processor/processor_job.i

# target to preprocess a source file
src/processor/processor_job.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-processor.dir/build.make CMakeFiles/bpbd-processor.dir/src/processor/processor_job.cpp.i
.PHONY : src/processor/processor_job.cpp.i

src/processor/processor_job.s: src/processor/processor_job.cpp.s

.PHONY : src/processor/processor_job.s

# target to generate assembly for a file
src/processor/processor_job.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-processor.dir/build.make CMakeFiles/bpbd-processor.dir/src/processor/processor_job.cpp.s
.PHONY : src/processor/processor_job.cpp.s

src/processor/processor_parameters.o: src/processor/processor_parameters.cpp.o

.PHONY : src/processor/processor_parameters.o

# target to build an object file
src/processor/processor_parameters.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-processor.dir/build.make CMakeFiles/bpbd-processor.dir/src/processor/processor_parameters.cpp.o
.PHONY : src/processor/processor_parameters.cpp.o

src/processor/processor_parameters.i: src/processor/processor_parameters.cpp.i

.PHONY : src/processor/processor_parameters.i

# target to preprocess a source file
src/processor/processor_parameters.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-processor.dir/build.make CMakeFiles/bpbd-processor.dir/src/processor/processor_parameters.cpp.i
.PHONY : src/processor/processor_parameters.cpp.i

src/processor/processor_parameters.s: src/processor/processor_parameters.cpp.s

.PHONY : src/processor/processor_parameters.s

# target to generate assembly for a file
src/processor/processor_parameters.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-processor.dir/build.make CMakeFiles/bpbd-processor.dir/src/processor/processor_parameters.cpp.s
.PHONY : src/processor/processor_parameters.cpp.s

src/server/bpbd_server.o: src/server/bpbd_server.cpp.o

.PHONY : src/server/bpbd_server.o

# target to build an object file
src/server/bpbd_server.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/bpbd_server.cpp.o
.PHONY : src/server/bpbd_server.cpp.o

src/server/bpbd_server.i: src/server/bpbd_server.cpp.i

.PHONY : src/server/bpbd_server.i

# target to preprocess a source file
src/server/bpbd_server.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/bpbd_server.cpp.i
.PHONY : src/server/bpbd_server.cpp.i

src/server/bpbd_server.s: src/server/bpbd_server.cpp.s

.PHONY : src/server/bpbd_server.s

# target to generate assembly for a file
src/server/bpbd_server.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/bpbd_server.cpp.s
.PHONY : src/server/bpbd_server.cpp.s

src/server/decoder/de_configurator.o: src/server/decoder/de_configurator.cpp.o

.PHONY : src/server/decoder/de_configurator.o

# target to build an object file
src/server/decoder/de_configurator.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/decoder/de_configurator.cpp.o
.PHONY : src/server/decoder/de_configurator.cpp.o

src/server/decoder/de_configurator.i: src/server/decoder/de_configurator.cpp.i

.PHONY : src/server/decoder/de_configurator.i

# target to preprocess a source file
src/server/decoder/de_configurator.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/decoder/de_configurator.cpp.i
.PHONY : src/server/decoder/de_configurator.cpp.i

src/server/decoder/de_configurator.s: src/server/decoder/de_configurator.cpp.s

.PHONY : src/server/decoder/de_configurator.s

# target to generate assembly for a file
src/server/decoder/de_configurator.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/decoder/de_configurator.cpp.s
.PHONY : src/server/decoder/de_configurator.cpp.s

src/server/decoder/de_parameters.o: src/server/decoder/de_parameters.cpp.o

.PHONY : src/server/decoder/de_parameters.o

# target to build an object file
src/server/decoder/de_parameters.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/decoder/de_parameters.cpp.o
.PHONY : src/server/decoder/de_parameters.cpp.o

src/server/decoder/de_parameters.i: src/server/decoder/de_parameters.cpp.i

.PHONY : src/server/decoder/de_parameters.i

# target to preprocess a source file
src/server/decoder/de_parameters.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/decoder/de_parameters.cpp.i
.PHONY : src/server/decoder/de_parameters.cpp.i

src/server/decoder/de_parameters.s: src/server/decoder/de_parameters.cpp.s

.PHONY : src/server/decoder/de_parameters.s

# target to generate assembly for a file
src/server/decoder/de_parameters.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/decoder/de_parameters.cpp.s
.PHONY : src/server/decoder/de_parameters.cpp.s

src/server/lm/builders/lm_basic_builder.o: src/server/lm/builders/lm_basic_builder.cpp.o

.PHONY : src/server/lm/builders/lm_basic_builder.o

# target to build an object file
src/server/lm/builders/lm_basic_builder.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/builders/lm_basic_builder.cpp.o
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/builders/lm_basic_builder.cpp.o
.PHONY : src/server/lm/builders/lm_basic_builder.cpp.o

src/server/lm/builders/lm_basic_builder.i: src/server/lm/builders/lm_basic_builder.cpp.i

.PHONY : src/server/lm/builders/lm_basic_builder.i

# target to preprocess a source file
src/server/lm/builders/lm_basic_builder.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/builders/lm_basic_builder.cpp.i
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/builders/lm_basic_builder.cpp.i
.PHONY : src/server/lm/builders/lm_basic_builder.cpp.i

src/server/lm/builders/lm_basic_builder.s: src/server/lm/builders/lm_basic_builder.cpp.s

.PHONY : src/server/lm/builders/lm_basic_builder.s

# target to generate assembly for a file
src/server/lm/builders/lm_basic_builder.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/builders/lm_basic_builder.cpp.s
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/builders/lm_basic_builder.cpp.s
.PHONY : src/server/lm/builders/lm_basic_builder.cpp.s

src/server/lm/builders/lm_gram_builder.o: src/server/lm/builders/lm_gram_builder.cpp.o

.PHONY : src/server/lm/builders/lm_gram_builder.o

# target to build an object file
src/server/lm/builders/lm_gram_builder.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/builders/lm_gram_builder.cpp.o
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/builders/lm_gram_builder.cpp.o
.PHONY : src/server/lm/builders/lm_gram_builder.cpp.o

src/server/lm/builders/lm_gram_builder.i: src/server/lm/builders/lm_gram_builder.cpp.i

.PHONY : src/server/lm/builders/lm_gram_builder.i

# target to preprocess a source file
src/server/lm/builders/lm_gram_builder.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/builders/lm_gram_builder.cpp.i
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/builders/lm_gram_builder.cpp.i
.PHONY : src/server/lm/builders/lm_gram_builder.cpp.i

src/server/lm/builders/lm_gram_builder.s: src/server/lm/builders/lm_gram_builder.cpp.s

.PHONY : src/server/lm/builders/lm_gram_builder.s

# target to generate assembly for a file
src/server/lm/builders/lm_gram_builder.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/builders/lm_gram_builder.cpp.s
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/builders/lm_gram_builder.cpp.s
.PHONY : src/server/lm/builders/lm_gram_builder.cpp.s

src/server/lm/lm_configurator.o: src/server/lm/lm_configurator.cpp.o

.PHONY : src/server/lm/lm_configurator.o

# target to build an object file
src/server/lm/lm_configurator.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/lm_configurator.cpp.o
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/lm_configurator.cpp.o
.PHONY : src/server/lm/lm_configurator.cpp.o

src/server/lm/lm_configurator.i: src/server/lm/lm_configurator.cpp.i

.PHONY : src/server/lm/lm_configurator.i

# target to preprocess a source file
src/server/lm/lm_configurator.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/lm_configurator.cpp.i
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/lm_configurator.cpp.i
.PHONY : src/server/lm/lm_configurator.cpp.i

src/server/lm/lm_configurator.s: src/server/lm/lm_configurator.cpp.s

.PHONY : src/server/lm/lm_configurator.s

# target to generate assembly for a file
src/server/lm/lm_configurator.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/lm_configurator.cpp.s
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/lm_configurator.cpp.s
.PHONY : src/server/lm/lm_configurator.cpp.s

src/server/lm/lm_parameters.o: src/server/lm/lm_parameters.cpp.o

.PHONY : src/server/lm/lm_parameters.o

# target to build an object file
src/server/lm/lm_parameters.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/lm_parameters.cpp.o
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/lm_parameters.cpp.o
.PHONY : src/server/lm/lm_parameters.cpp.o

src/server/lm/lm_parameters.i: src/server/lm/lm_parameters.cpp.i

.PHONY : src/server/lm/lm_parameters.i

# target to preprocess a source file
src/server/lm/lm_parameters.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/lm_parameters.cpp.i
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/lm_parameters.cpp.i
.PHONY : src/server/lm/lm_parameters.cpp.i

src/server/lm/lm_parameters.s: src/server/lm/lm_parameters.cpp.s

.PHONY : src/server/lm/lm_parameters.s

# target to generate assembly for a file
src/server/lm/lm_parameters.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/lm_parameters.cpp.s
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/lm_parameters.cpp.s
.PHONY : src/server/lm/lm_parameters.cpp.s

src/server/lm/lm_query.o: src/server/lm/lm_query.cpp.o

.PHONY : src/server/lm/lm_query.o

# target to build an object file
src/server/lm/lm_query.cpp.o:
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/lm_query.cpp.o
.PHONY : src/server/lm/lm_query.cpp.o

src/server/lm/lm_query.i: src/server/lm/lm_query.cpp.i

.PHONY : src/server/lm/lm_query.i

# target to preprocess a source file
src/server/lm/lm_query.cpp.i:
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/lm_query.cpp.i
.PHONY : src/server/lm/lm_query.cpp.i

src/server/lm/lm_query.s: src/server/lm/lm_query.cpp.s

.PHONY : src/server/lm/lm_query.s

# target to generate assembly for a file
src/server/lm/lm_query.cpp.s:
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/lm_query.cpp.s
.PHONY : src/server/lm/lm_query.cpp.s

src/server/lm/mgrams/byte_m_gram_id.o: src/server/lm/mgrams/byte_m_gram_id.cpp.o

.PHONY : src/server/lm/mgrams/byte_m_gram_id.o

# target to build an object file
src/server/lm/mgrams/byte_m_gram_id.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/mgrams/byte_m_gram_id.cpp.o
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/mgrams/byte_m_gram_id.cpp.o
.PHONY : src/server/lm/mgrams/byte_m_gram_id.cpp.o

src/server/lm/mgrams/byte_m_gram_id.i: src/server/lm/mgrams/byte_m_gram_id.cpp.i

.PHONY : src/server/lm/mgrams/byte_m_gram_id.i

# target to preprocess a source file
src/server/lm/mgrams/byte_m_gram_id.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/mgrams/byte_m_gram_id.cpp.i
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/mgrams/byte_m_gram_id.cpp.i
.PHONY : src/server/lm/mgrams/byte_m_gram_id.cpp.i

src/server/lm/mgrams/byte_m_gram_id.s: src/server/lm/mgrams/byte_m_gram_id.cpp.s

.PHONY : src/server/lm/mgrams/byte_m_gram_id.s

# target to generate assembly for a file
src/server/lm/mgrams/byte_m_gram_id.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/mgrams/byte_m_gram_id.cpp.s
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/mgrams/byte_m_gram_id.cpp.s
.PHONY : src/server/lm/mgrams/byte_m_gram_id.cpp.s

src/server/lm/mgrams/model_m_gram.o: src/server/lm/mgrams/model_m_gram.cpp.o

.PHONY : src/server/lm/mgrams/model_m_gram.o

# target to build an object file
src/server/lm/mgrams/model_m_gram.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/mgrams/model_m_gram.cpp.o
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/mgrams/model_m_gram.cpp.o
.PHONY : src/server/lm/mgrams/model_m_gram.cpp.o

src/server/lm/mgrams/model_m_gram.i: src/server/lm/mgrams/model_m_gram.cpp.i

.PHONY : src/server/lm/mgrams/model_m_gram.i

# target to preprocess a source file
src/server/lm/mgrams/model_m_gram.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/mgrams/model_m_gram.cpp.i
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/mgrams/model_m_gram.cpp.i
.PHONY : src/server/lm/mgrams/model_m_gram.cpp.i

src/server/lm/mgrams/model_m_gram.s: src/server/lm/mgrams/model_m_gram.cpp.s

.PHONY : src/server/lm/mgrams/model_m_gram.s

# target to generate assembly for a file
src/server/lm/mgrams/model_m_gram.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/mgrams/model_m_gram.cpp.s
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/mgrams/model_m_gram.cpp.s
.PHONY : src/server/lm/mgrams/model_m_gram.cpp.s

src/server/lm/mgrams/query_m_gram.o: src/server/lm/mgrams/query_m_gram.cpp.o

.PHONY : src/server/lm/mgrams/query_m_gram.o

# target to build an object file
src/server/lm/mgrams/query_m_gram.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/mgrams/query_m_gram.cpp.o
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/mgrams/query_m_gram.cpp.o
.PHONY : src/server/lm/mgrams/query_m_gram.cpp.o

src/server/lm/mgrams/query_m_gram.i: src/server/lm/mgrams/query_m_gram.cpp.i

.PHONY : src/server/lm/mgrams/query_m_gram.i

# target to preprocess a source file
src/server/lm/mgrams/query_m_gram.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/mgrams/query_m_gram.cpp.i
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/mgrams/query_m_gram.cpp.i
.PHONY : src/server/lm/mgrams/query_m_gram.cpp.i

src/server/lm/mgrams/query_m_gram.s: src/server/lm/mgrams/query_m_gram.cpp.s

.PHONY : src/server/lm/mgrams/query_m_gram.s

# target to generate assembly for a file
src/server/lm/mgrams/query_m_gram.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/mgrams/query_m_gram.cpp.s
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/mgrams/query_m_gram.cpp.s
.PHONY : src/server/lm/mgrams/query_m_gram.cpp.s

src/server/lm/models/c2d_hybrid_trie.o: src/server/lm/models/c2d_hybrid_trie.cpp.o

.PHONY : src/server/lm/models/c2d_hybrid_trie.o

# target to build an object file
src/server/lm/models/c2d_hybrid_trie.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/models/c2d_hybrid_trie.cpp.o
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/models/c2d_hybrid_trie.cpp.o
.PHONY : src/server/lm/models/c2d_hybrid_trie.cpp.o

src/server/lm/models/c2d_hybrid_trie.i: src/server/lm/models/c2d_hybrid_trie.cpp.i

.PHONY : src/server/lm/models/c2d_hybrid_trie.i

# target to preprocess a source file
src/server/lm/models/c2d_hybrid_trie.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/models/c2d_hybrid_trie.cpp.i
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/models/c2d_hybrid_trie.cpp.i
.PHONY : src/server/lm/models/c2d_hybrid_trie.cpp.i

src/server/lm/models/c2d_hybrid_trie.s: src/server/lm/models/c2d_hybrid_trie.cpp.s

.PHONY : src/server/lm/models/c2d_hybrid_trie.s

# target to generate assembly for a file
src/server/lm/models/c2d_hybrid_trie.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/models/c2d_hybrid_trie.cpp.s
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/models/c2d_hybrid_trie.cpp.s
.PHONY : src/server/lm/models/c2d_hybrid_trie.cpp.s

src/server/lm/models/c2d_map_trie.o: src/server/lm/models/c2d_map_trie.cpp.o

.PHONY : src/server/lm/models/c2d_map_trie.o

# target to build an object file
src/server/lm/models/c2d_map_trie.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/models/c2d_map_trie.cpp.o
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/models/c2d_map_trie.cpp.o
.PHONY : src/server/lm/models/c2d_map_trie.cpp.o

src/server/lm/models/c2d_map_trie.i: src/server/lm/models/c2d_map_trie.cpp.i

.PHONY : src/server/lm/models/c2d_map_trie.i

# target to preprocess a source file
src/server/lm/models/c2d_map_trie.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/models/c2d_map_trie.cpp.i
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/models/c2d_map_trie.cpp.i
.PHONY : src/server/lm/models/c2d_map_trie.cpp.i

src/server/lm/models/c2d_map_trie.s: src/server/lm/models/c2d_map_trie.cpp.s

.PHONY : src/server/lm/models/c2d_map_trie.s

# target to generate assembly for a file
src/server/lm/models/c2d_map_trie.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/models/c2d_map_trie.cpp.s
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/models/c2d_map_trie.cpp.s
.PHONY : src/server/lm/models/c2d_map_trie.cpp.s

src/server/lm/models/c2w_array_trie.o: src/server/lm/models/c2w_array_trie.cpp.o

.PHONY : src/server/lm/models/c2w_array_trie.o

# target to build an object file
src/server/lm/models/c2w_array_trie.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/models/c2w_array_trie.cpp.o
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/models/c2w_array_trie.cpp.o
.PHONY : src/server/lm/models/c2w_array_trie.cpp.o

src/server/lm/models/c2w_array_trie.i: src/server/lm/models/c2w_array_trie.cpp.i

.PHONY : src/server/lm/models/c2w_array_trie.i

# target to preprocess a source file
src/server/lm/models/c2w_array_trie.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/models/c2w_array_trie.cpp.i
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/models/c2w_array_trie.cpp.i
.PHONY : src/server/lm/models/c2w_array_trie.cpp.i

src/server/lm/models/c2w_array_trie.s: src/server/lm/models/c2w_array_trie.cpp.s

.PHONY : src/server/lm/models/c2w_array_trie.s

# target to generate assembly for a file
src/server/lm/models/c2w_array_trie.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/models/c2w_array_trie.cpp.s
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/models/c2w_array_trie.cpp.s
.PHONY : src/server/lm/models/c2w_array_trie.cpp.s

src/server/lm/models/g2d_map_trie.o: src/server/lm/models/g2d_map_trie.cpp.o

.PHONY : src/server/lm/models/g2d_map_trie.o

# target to build an object file
src/server/lm/models/g2d_map_trie.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/models/g2d_map_trie.cpp.o
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/models/g2d_map_trie.cpp.o
.PHONY : src/server/lm/models/g2d_map_trie.cpp.o

src/server/lm/models/g2d_map_trie.i: src/server/lm/models/g2d_map_trie.cpp.i

.PHONY : src/server/lm/models/g2d_map_trie.i

# target to preprocess a source file
src/server/lm/models/g2d_map_trie.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/models/g2d_map_trie.cpp.i
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/models/g2d_map_trie.cpp.i
.PHONY : src/server/lm/models/g2d_map_trie.cpp.i

src/server/lm/models/g2d_map_trie.s: src/server/lm/models/g2d_map_trie.cpp.s

.PHONY : src/server/lm/models/g2d_map_trie.s

# target to generate assembly for a file
src/server/lm/models/g2d_map_trie.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/models/g2d_map_trie.cpp.s
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/models/g2d_map_trie.cpp.s
.PHONY : src/server/lm/models/g2d_map_trie.cpp.s

src/server/lm/models/h2d_map_trie.o: src/server/lm/models/h2d_map_trie.cpp.o

.PHONY : src/server/lm/models/h2d_map_trie.o

# target to build an object file
src/server/lm/models/h2d_map_trie.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/models/h2d_map_trie.cpp.o
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/models/h2d_map_trie.cpp.o
.PHONY : src/server/lm/models/h2d_map_trie.cpp.o

src/server/lm/models/h2d_map_trie.i: src/server/lm/models/h2d_map_trie.cpp.i

.PHONY : src/server/lm/models/h2d_map_trie.i

# target to preprocess a source file
src/server/lm/models/h2d_map_trie.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/models/h2d_map_trie.cpp.i
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/models/h2d_map_trie.cpp.i
.PHONY : src/server/lm/models/h2d_map_trie.cpp.i

src/server/lm/models/h2d_map_trie.s: src/server/lm/models/h2d_map_trie.cpp.s

.PHONY : src/server/lm/models/h2d_map_trie.s

# target to generate assembly for a file
src/server/lm/models/h2d_map_trie.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/models/h2d_map_trie.cpp.s
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/models/h2d_map_trie.cpp.s
.PHONY : src/server/lm/models/h2d_map_trie.cpp.s

src/server/lm/models/m_gram_query.o: src/server/lm/models/m_gram_query.cpp.o

.PHONY : src/server/lm/models/m_gram_query.o

# target to build an object file
src/server/lm/models/m_gram_query.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/models/m_gram_query.cpp.o
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/models/m_gram_query.cpp.o
.PHONY : src/server/lm/models/m_gram_query.cpp.o

src/server/lm/models/m_gram_query.i: src/server/lm/models/m_gram_query.cpp.i

.PHONY : src/server/lm/models/m_gram_query.i

# target to preprocess a source file
src/server/lm/models/m_gram_query.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/models/m_gram_query.cpp.i
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/models/m_gram_query.cpp.i
.PHONY : src/server/lm/models/m_gram_query.cpp.i

src/server/lm/models/m_gram_query.s: src/server/lm/models/m_gram_query.cpp.s

.PHONY : src/server/lm/models/m_gram_query.s

# target to generate assembly for a file
src/server/lm/models/m_gram_query.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/models/m_gram_query.cpp.s
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/models/m_gram_query.cpp.s
.PHONY : src/server/lm/models/m_gram_query.cpp.s

src/server/lm/models/w2c_array_trie.o: src/server/lm/models/w2c_array_trie.cpp.o

.PHONY : src/server/lm/models/w2c_array_trie.o

# target to build an object file
src/server/lm/models/w2c_array_trie.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/models/w2c_array_trie.cpp.o
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/models/w2c_array_trie.cpp.o
.PHONY : src/server/lm/models/w2c_array_trie.cpp.o

src/server/lm/models/w2c_array_trie.i: src/server/lm/models/w2c_array_trie.cpp.i

.PHONY : src/server/lm/models/w2c_array_trie.i

# target to preprocess a source file
src/server/lm/models/w2c_array_trie.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/models/w2c_array_trie.cpp.i
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/models/w2c_array_trie.cpp.i
.PHONY : src/server/lm/models/w2c_array_trie.cpp.i

src/server/lm/models/w2c_array_trie.s: src/server/lm/models/w2c_array_trie.cpp.s

.PHONY : src/server/lm/models/w2c_array_trie.s

# target to generate assembly for a file
src/server/lm/models/w2c_array_trie.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/models/w2c_array_trie.cpp.s
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/models/w2c_array_trie.cpp.s
.PHONY : src/server/lm/models/w2c_array_trie.cpp.s

src/server/lm/models/w2c_hybrid_trie.o: src/server/lm/models/w2c_hybrid_trie.cpp.o

.PHONY : src/server/lm/models/w2c_hybrid_trie.o

# target to build an object file
src/server/lm/models/w2c_hybrid_trie.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/models/w2c_hybrid_trie.cpp.o
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/models/w2c_hybrid_trie.cpp.o
.PHONY : src/server/lm/models/w2c_hybrid_trie.cpp.o

src/server/lm/models/w2c_hybrid_trie.i: src/server/lm/models/w2c_hybrid_trie.cpp.i

.PHONY : src/server/lm/models/w2c_hybrid_trie.i

# target to preprocess a source file
src/server/lm/models/w2c_hybrid_trie.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/models/w2c_hybrid_trie.cpp.i
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/models/w2c_hybrid_trie.cpp.i
.PHONY : src/server/lm/models/w2c_hybrid_trie.cpp.i

src/server/lm/models/w2c_hybrid_trie.s: src/server/lm/models/w2c_hybrid_trie.cpp.s

.PHONY : src/server/lm/models/w2c_hybrid_trie.s

# target to generate assembly for a file
src/server/lm/models/w2c_hybrid_trie.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/lm/models/w2c_hybrid_trie.cpp.s
	$(MAKE) -f CMakeFiles/lm-query.dir/build.make CMakeFiles/lm-query.dir/src/server/lm/models/w2c_hybrid_trie.cpp.s
.PHONY : src/server/lm/models/w2c_hybrid_trie.cpp.s

src/server/messaging/messaging.o: src/server/messaging/messaging.cpp.o

.PHONY : src/server/messaging/messaging.o

# target to build an object file
src/server/messaging/messaging.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/messaging/messaging.cpp.o
.PHONY : src/server/messaging/messaging.cpp.o

src/server/messaging/messaging.i: src/server/messaging/messaging.cpp.i

.PHONY : src/server/messaging/messaging.i

# target to preprocess a source file
src/server/messaging/messaging.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/messaging/messaging.cpp.i
.PHONY : src/server/messaging/messaging.cpp.i

src/server/messaging/messaging.s: src/server/messaging/messaging.cpp.s

.PHONY : src/server/messaging/messaging.s

# target to generate assembly for a file
src/server/messaging/messaging.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/messaging/messaging.cpp.s
.PHONY : src/server/messaging/messaging.cpp.s

src/server/rm/models/rm_entry.o: src/server/rm/models/rm_entry.cpp.o

.PHONY : src/server/rm/models/rm_entry.o

# target to build an object file
src/server/rm/models/rm_entry.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/rm/models/rm_entry.cpp.o
.PHONY : src/server/rm/models/rm_entry.cpp.o

src/server/rm/models/rm_entry.i: src/server/rm/models/rm_entry.cpp.i

.PHONY : src/server/rm/models/rm_entry.i

# target to preprocess a source file
src/server/rm/models/rm_entry.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/rm/models/rm_entry.cpp.i
.PHONY : src/server/rm/models/rm_entry.cpp.i

src/server/rm/models/rm_entry.s: src/server/rm/models/rm_entry.cpp.s

.PHONY : src/server/rm/models/rm_entry.s

# target to generate assembly for a file
src/server/rm/models/rm_entry.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/rm/models/rm_entry.cpp.s
.PHONY : src/server/rm/models/rm_entry.cpp.s

src/server/rm/rm_configurator.o: src/server/rm/rm_configurator.cpp.o

.PHONY : src/server/rm/rm_configurator.o

# target to build an object file
src/server/rm/rm_configurator.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/rm/rm_configurator.cpp.o
.PHONY : src/server/rm/rm_configurator.cpp.o

src/server/rm/rm_configurator.i: src/server/rm/rm_configurator.cpp.i

.PHONY : src/server/rm/rm_configurator.i

# target to preprocess a source file
src/server/rm/rm_configurator.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/rm/rm_configurator.cpp.i
.PHONY : src/server/rm/rm_configurator.cpp.i

src/server/rm/rm_configurator.s: src/server/rm/rm_configurator.cpp.s

.PHONY : src/server/rm/rm_configurator.s

# target to generate assembly for a file
src/server/rm/rm_configurator.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/rm/rm_configurator.cpp.s
.PHONY : src/server/rm/rm_configurator.cpp.s

src/server/rm/rm_parameters.o: src/server/rm/rm_parameters.cpp.o

.PHONY : src/server/rm/rm_parameters.o

# target to build an object file
src/server/rm/rm_parameters.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/rm/rm_parameters.cpp.o
.PHONY : src/server/rm/rm_parameters.cpp.o

src/server/rm/rm_parameters.i: src/server/rm/rm_parameters.cpp.i

.PHONY : src/server/rm/rm_parameters.i

# target to preprocess a source file
src/server/rm/rm_parameters.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/rm/rm_parameters.cpp.i
.PHONY : src/server/rm/rm_parameters.cpp.i

src/server/rm/rm_parameters.s: src/server/rm/rm_parameters.cpp.s

.PHONY : src/server/rm/rm_parameters.s

# target to generate assembly for a file
src/server/rm/rm_parameters.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/rm/rm_parameters.cpp.s
.PHONY : src/server/rm/rm_parameters.cpp.s

src/server/server_parameters.o: src/server/server_parameters.cpp.o

.PHONY : src/server/server_parameters.o

# target to build an object file
src/server/server_parameters.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/server_parameters.cpp.o
.PHONY : src/server/server_parameters.cpp.o

src/server/server_parameters.i: src/server/server_parameters.cpp.i

.PHONY : src/server/server_parameters.i

# target to preprocess a source file
src/server/server_parameters.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/server_parameters.cpp.i
.PHONY : src/server/server_parameters.cpp.i

src/server/server_parameters.s: src/server/server_parameters.cpp.s

.PHONY : src/server/server_parameters.s

# target to generate assembly for a file
src/server/server_parameters.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/server_parameters.cpp.s
.PHONY : src/server/server_parameters.cpp.s

src/server/tm/models/tm_target_entry.o: src/server/tm/models/tm_target_entry.cpp.o

.PHONY : src/server/tm/models/tm_target_entry.o

# target to build an object file
src/server/tm/models/tm_target_entry.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/tm/models/tm_target_entry.cpp.o
.PHONY : src/server/tm/models/tm_target_entry.cpp.o

src/server/tm/models/tm_target_entry.i: src/server/tm/models/tm_target_entry.cpp.i

.PHONY : src/server/tm/models/tm_target_entry.i

# target to preprocess a source file
src/server/tm/models/tm_target_entry.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/tm/models/tm_target_entry.cpp.i
.PHONY : src/server/tm/models/tm_target_entry.cpp.i

src/server/tm/models/tm_target_entry.s: src/server/tm/models/tm_target_entry.cpp.s

.PHONY : src/server/tm/models/tm_target_entry.s

# target to generate assembly for a file
src/server/tm/models/tm_target_entry.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/tm/models/tm_target_entry.cpp.s
.PHONY : src/server/tm/models/tm_target_entry.cpp.s

src/server/tm/tm_configurator.o: src/server/tm/tm_configurator.cpp.o

.PHONY : src/server/tm/tm_configurator.o

# target to build an object file
src/server/tm/tm_configurator.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/tm/tm_configurator.cpp.o
.PHONY : src/server/tm/tm_configurator.cpp.o

src/server/tm/tm_configurator.i: src/server/tm/tm_configurator.cpp.i

.PHONY : src/server/tm/tm_configurator.i

# target to preprocess a source file
src/server/tm/tm_configurator.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/tm/tm_configurator.cpp.i
.PHONY : src/server/tm/tm_configurator.cpp.i

src/server/tm/tm_configurator.s: src/server/tm/tm_configurator.cpp.s

.PHONY : src/server/tm/tm_configurator.s

# target to generate assembly for a file
src/server/tm/tm_configurator.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/tm/tm_configurator.cpp.s
.PHONY : src/server/tm/tm_configurator.cpp.s

src/server/tm/tm_parameters.o: src/server/tm/tm_parameters.cpp.o

.PHONY : src/server/tm/tm_parameters.o

# target to build an object file
src/server/tm/tm_parameters.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/tm/tm_parameters.cpp.o
.PHONY : src/server/tm/tm_parameters.cpp.o

src/server/tm/tm_parameters.i: src/server/tm/tm_parameters.cpp.i

.PHONY : src/server/tm/tm_parameters.i

# target to preprocess a source file
src/server/tm/tm_parameters.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/tm/tm_parameters.cpp.i
.PHONY : src/server/tm/tm_parameters.cpp.i

src/server/tm/tm_parameters.s: src/server/tm/tm_parameters.cpp.s

.PHONY : src/server/tm/tm_parameters.s

# target to generate assembly for a file
src/server/tm/tm_parameters.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/tm/tm_parameters.cpp.s
.PHONY : src/server/tm/tm_parameters.cpp.s

src/server/trans_task.o: src/server/trans_task.cpp.o

.PHONY : src/server/trans_task.o

# target to build an object file
src/server/trans_task.cpp.o:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/trans_task.cpp.o
.PHONY : src/server/trans_task.cpp.o

src/server/trans_task.i: src/server/trans_task.cpp.i

.PHONY : src/server/trans_task.i

# target to preprocess a source file
src/server/trans_task.cpp.i:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/trans_task.cpp.i
.PHONY : src/server/trans_task.cpp.i

src/server/trans_task.s: src/server/trans_task.cpp.s

.PHONY : src/server/trans_task.s

# target to generate assembly for a file
src/server/trans_task.cpp.s:
	$(MAKE) -f CMakeFiles/bpbd-server.dir/build.make CMakeFiles/bpbd-server.dir/src/server/trans_task.cpp.s
.PHONY : src/server/trans_task.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... bpbd-client"
	@echo "... bpbd-processor"
	@echo "... bpbd-balancer"
	@echo "... bpbd-server"
	@echo "... lm-query"
	@echo "... src/balancer/balancer_job.o"
	@echo "... src/balancer/balancer_job.i"
	@echo "... src/balancer/balancer_job.s"
	@echo "... src/balancer/balancer_parameters.o"
	@echo "... src/balancer/balancer_parameters.i"
	@echo "... src/balancer/balancer_parameters.s"
	@echo "... src/balancer/bpbd_balancer.o"
	@echo "... src/balancer/bpbd_balancer.i"
	@echo "... src/balancer/bpbd_balancer.s"
	@echo "... src/balancer/translator_adapter.o"
	@echo "... src/balancer/translator_adapter.i"
	@echo "... src/balancer/translator_adapter.s"
	@echo "... src/client/bpbd_client.o"
	@echo "... src/client/bpbd_client.i"
	@echo "... src/client/bpbd_client.s"
	@echo "... src/client/messaging/messaging.o"
	@echo "... src/client/messaging/messaging.i"
	@echo "... src/client/messaging/messaging.s"
	@echo "... src/client/trans_job_status.o"
	@echo "... src/client/trans_job_status.i"
	@echo "... src/client/trans_job_status.s"
	@echo "... src/common/messaging/language_registry.o"
	@echo "... src/common/messaging/language_registry.i"
	@echo "... src/common/messaging/language_registry.s"
	@echo "... src/common/messaging/messaging.o"
	@echo "... src/common/messaging/messaging.i"
	@echo "... src/common/messaging/messaging.s"
	@echo "... src/common/messaging/trans_job_code.o"
	@echo "... src/common/messaging/trans_job_code.i"
	@echo "... src/common/messaging/trans_job_code.s"
	@echo "... src/common/utils/logging/logger.o"
	@echo "... src/common/utils/logging/logger.i"
	@echo "... src/common/utils/logging/logger.s"
	@echo "... src/common/utils/monitor/statistics_monitor.o"
	@echo "... src/common/utils/monitor/statistics_monitor.i"
	@echo "... src/common/utils/monitor/statistics_monitor.s"
	@echo "... src/processor/bpbd_processor.o"
	@echo "... src/processor/bpbd_processor.i"
	@echo "... src/processor/bpbd_processor.s"
	@echo "... src/processor/processor_job.o"
	@echo "... src/processor/processor_job.i"
	@echo "... src/processor/processor_job.s"
	@echo "... src/processor/processor_parameters.o"
	@echo "... src/processor/processor_parameters.i"
	@echo "... src/processor/processor_parameters.s"
	@echo "... src/server/bpbd_server.o"
	@echo "... src/server/bpbd_server.i"
	@echo "... src/server/bpbd_server.s"
	@echo "... src/server/decoder/de_configurator.o"
	@echo "... src/server/decoder/de_configurator.i"
	@echo "... src/server/decoder/de_configurator.s"
	@echo "... src/server/decoder/de_parameters.o"
	@echo "... src/server/decoder/de_parameters.i"
	@echo "... src/server/decoder/de_parameters.s"
	@echo "... src/server/lm/builders/lm_basic_builder.o"
	@echo "... src/server/lm/builders/lm_basic_builder.i"
	@echo "... src/server/lm/builders/lm_basic_builder.s"
	@echo "... src/server/lm/builders/lm_gram_builder.o"
	@echo "... src/server/lm/builders/lm_gram_builder.i"
	@echo "... src/server/lm/builders/lm_gram_builder.s"
	@echo "... src/server/lm/lm_configurator.o"
	@echo "... src/server/lm/lm_configurator.i"
	@echo "... src/server/lm/lm_configurator.s"
	@echo "... src/server/lm/lm_parameters.o"
	@echo "... src/server/lm/lm_parameters.i"
	@echo "... src/server/lm/lm_parameters.s"
	@echo "... src/server/lm/lm_query.o"
	@echo "... src/server/lm/lm_query.i"
	@echo "... src/server/lm/lm_query.s"
	@echo "... src/server/lm/mgrams/byte_m_gram_id.o"
	@echo "... src/server/lm/mgrams/byte_m_gram_id.i"
	@echo "... src/server/lm/mgrams/byte_m_gram_id.s"
	@echo "... src/server/lm/mgrams/model_m_gram.o"
	@echo "... src/server/lm/mgrams/model_m_gram.i"
	@echo "... src/server/lm/mgrams/model_m_gram.s"
	@echo "... src/server/lm/mgrams/query_m_gram.o"
	@echo "... src/server/lm/mgrams/query_m_gram.i"
	@echo "... src/server/lm/mgrams/query_m_gram.s"
	@echo "... src/server/lm/models/c2d_hybrid_trie.o"
	@echo "... src/server/lm/models/c2d_hybrid_trie.i"
	@echo "... src/server/lm/models/c2d_hybrid_trie.s"
	@echo "... src/server/lm/models/c2d_map_trie.o"
	@echo "... src/server/lm/models/c2d_map_trie.i"
	@echo "... src/server/lm/models/c2d_map_trie.s"
	@echo "... src/server/lm/models/c2w_array_trie.o"
	@echo "... src/server/lm/models/c2w_array_trie.i"
	@echo "... src/server/lm/models/c2w_array_trie.s"
	@echo "... src/server/lm/models/g2d_map_trie.o"
	@echo "... src/server/lm/models/g2d_map_trie.i"
	@echo "... src/server/lm/models/g2d_map_trie.s"
	@echo "... src/server/lm/models/h2d_map_trie.o"
	@echo "... src/server/lm/models/h2d_map_trie.i"
	@echo "... src/server/lm/models/h2d_map_trie.s"
	@echo "... src/server/lm/models/m_gram_query.o"
	@echo "... src/server/lm/models/m_gram_query.i"
	@echo "... src/server/lm/models/m_gram_query.s"
	@echo "... src/server/lm/models/w2c_array_trie.o"
	@echo "... src/server/lm/models/w2c_array_trie.i"
	@echo "... src/server/lm/models/w2c_array_trie.s"
	@echo "... src/server/lm/models/w2c_hybrid_trie.o"
	@echo "... src/server/lm/models/w2c_hybrid_trie.i"
	@echo "... src/server/lm/models/w2c_hybrid_trie.s"
	@echo "... src/server/messaging/messaging.o"
	@echo "... src/server/messaging/messaging.i"
	@echo "... src/server/messaging/messaging.s"
	@echo "... src/server/rm/models/rm_entry.o"
	@echo "... src/server/rm/models/rm_entry.i"
	@echo "... src/server/rm/models/rm_entry.s"
	@echo "... src/server/rm/rm_configurator.o"
	@echo "... src/server/rm/rm_configurator.i"
	@echo "... src/server/rm/rm_configurator.s"
	@echo "... src/server/rm/rm_parameters.o"
	@echo "... src/server/rm/rm_parameters.i"
	@echo "... src/server/rm/rm_parameters.s"
	@echo "... src/server/server_parameters.o"
	@echo "... src/server/server_parameters.i"
	@echo "... src/server/server_parameters.s"
	@echo "... src/server/tm/models/tm_target_entry.o"
	@echo "... src/server/tm/models/tm_target_entry.i"
	@echo "... src/server/tm/models/tm_target_entry.s"
	@echo "... src/server/tm/tm_configurator.o"
	@echo "... src/server/tm/tm_configurator.i"
	@echo "... src/server/tm/tm_configurator.s"
	@echo "... src/server/tm/tm_parameters.o"
	@echo "... src/server/tm/tm_parameters.i"
	@echo "... src/server/tm/tm_parameters.s"
	@echo "... src/server/trans_task.o"
	@echo "... src/server/trans_task.i"
	@echo "... src/server/trans_task.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

