#!/bin/sh

unset LANG

#if [ $OWLTUNERHOME ]; then
#    echo "\$OWLTUNERHOME=$OWLTUNERHOME"
#else
#    echo environment variable OWLTUNERHOME must be set:
#    echo export OWLTUNERHOME=/path-to-owl/script/tuning
#    exit 1
#fi

BASEDIR=$(dirname "$0")

if [ $SMTAMS ]; then
    echo "\$SMTAMS=$SMTAMS"
else
    echo environment variable SMTAMS must be set:
    echo export STMAMS=/path/to/smtams
    exit 1
fi

echo "Process runnning on: $HOSTNAME"
time=`date`
echo "Started at: $time"


export EVAL=$SMTAMS/data/translation_test/OpenMT/mt04/chinese-english/
export SRCTXT=$EVAL/mt04.chinese-english.src.tok_stanford-ctb.txt
export REFTXT=$EVAL/mt04.chinese-english.ref.tok.txt

export TUNER="--mert-script=PRO-14"
export EXTPATH=$BASEDIR/megam_0.92/
export TUNING_OPTIONS="--conf=server.cfg --no-parallel=2 --trace=1 --nbest-size=1500 --src-language=chinese $TUNER"

$BASEDIR/scripts/oister-tuner.pl --src=$SRCTXT --node-scoring --ref=$REFTXT. --decoder=$BASEDIR/startServerClient_multiCore.sh --external-path=$EXTPATH $TUNING_OPTIONS
